export interface InvoiceHeader {
  invoiceauthorization: string;
  startdate: string;
  enddate: string;
  prefix: string;
  rfrom: number;
  rto: number;
  invoice: string;
  issuedate: string;
  issuetime: string;
  datein: string;
  dateout: string;
  observation: string;
  producedby: string;
  printdate: string;
  codediscount: string;
  register: string;
  typeinvoce: number;
  contract: string;
  identificationpatient: string;
  companyaccountid: number;
  companytypedocument: number;
  companydocument: string;
  companyname: string;
  companydepartment: string;
  companycity: string;
  companyaddress: string;
  companyregimen: number;
  companytelephone: string;
  clientaccountid: number;
  clienttypedocument: number;
  clientdocument: string;
  clientdepartment: string;
  clientcity: string;
  clientaddress: string;
  clientregimen: number;
  clientname: string;
  clienttelephone: string;
  clientemail: string;
  plan: string;
  firstname: string;
  familyname: string;
  middlename: string;
  paymentduedate: string;
  subtotal: number;
  totaldiscount: number;
  total: number;
}

export interface InvoiceBody {
  id: number;
  description: string;
  servicio?: string;
  concepto?: string;
  invoicedquantity: number;
  lineextensionamount: number;
  priceamount: number;
  totalconcepto?: number;
}